runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

# [START skip_files]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
